### ISSUE TITLE
Wrong links when logged out ( = visitor) and missing marriage block

### ISSUE THREAD

**Issue by hartenthaler** [JustCarmen/webtrees-fancy-treeview#105]
The link from one generation to the other is wrong (2.3 -> 2.4) if I'm a visitor. When I'm logged in, everything is ok.

There is no information about the marriage and the partnership when logged out. Both partners are dead. They have living children, but that should not matter in this case. When logged in, everything is ok.

![Screenshot (129)](https://user-images.githubusercontent.com/6324175/207990292-d6ccb262-f87d-4de8-9816-ee09ce4cf71f.png)

**Comment by JustCarmen** [comment]
The numbering that's a bug.

Don't know if the marriage details are missing or not shown because one of the family members is private. Does webtrees show a family page?

**Comment by hartenthaler** [comment]
You are right about not showing the families. Karl, his first partner Ruth and his later wife are all dead, but the wife died this year, so she is still a bit private. And because of the living children in the first partnership and the second marriage, those families cannot be shown in detail. This is not a bug, it is fancy correct!
![Screenshot (139)](https://user-images.githubusercontent.com/6324175/208208111-6aa0c444-6c22-4b7f-840f-3ec751d7debf.png)
