### ISSUE TITLE
button "Add to menu"

### ISSUE THREAD

**Issue by Fa10175** [JustCarmen/webtrees-fancy-treeview#109]
this button "Add to menu" is show for the administror after the first page and after click on button "more information"

why is no display before .

if you want to highlight a tree on a page, you can't because these conditions are not possible.

we should have for the administrator at the top the button  "Add to menu" always.

at the bottom we would have the list of available pages.

**Comment by JustCarmen** [comment]
When on the tab page you can use the links in the individual edit menu:

![image](https://user-images.githubusercontent.com/5641963/208179493-dfe58a01-c9f5-43cc-b870-23ec573fa463.png)

**Comment by Fa10175** [comment]
I had not seen this possibility and more easy
