### ISSUE TITLE
Odd crash when selecting another tree from one that has no problem.

### ISSUE THREAD

**Issue by WGroleau** [JustCarmen/webtrees-fancy-treeview#111]
I recently created a separate tree and added a small number of records (see image).  Without changing any "fancy" modules, I did update webtrees core and the Vesta modules.  After doing so, the first time I selected that tree from the "family trees" menu, I got a stack dump.  Everything on the larger default tree seems to work.  I then downloaded the latest jc modules (all four) and installed.  I disabled image-bar and research links and left tree view and just light enabled.  Selected "bible" and got the same crash.  Again, the other tree seems OK—but I can't check what happens when selecting it, because the menu isn't available unless it is already selected.  Control panel also works, and I did "Check errors" on that tree—no errors.  "Find duplicates" found none and  "unrelated individuals" found many (as expected).

Here is the beginning of the stack trace:

Call to a member function canShow() on null …/modules_v4/jc-fancy-treeview/FancyTreeviewModule.php:417
#0 …/app/Module/ModuleThemeTrait.php(495): JustCarmen\Webtrees\Module\FancyTreeview\FancyTreeviewModule->getMenu()
#1 [internal function]: JustCarmen\Webtrees\Module\JustlightTheme\JustlightTheme::Fisharebest\Webtrees\Module\{closure}()
#2 …/vendor/illuminate/collections/Collection.php(695): array_map()
#3 …/app/Module/ModuleThemeTrait.php(495): Illuminate\Support\Collection->map()
#4 …/modules_v4/jc-theme-justlight/resources/views/layouts/body/primary-navigation.phtml(13): JustCarmen\Webtrees\Module\JustlightTheme\JustlightTheme->genealogyMenu()
#5 …/app/View.php(183): include('...')
#6 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#7 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#8 …/modules_v4/vesta_classic_look_and_feel/resources/views/layouts/defaultJustLight.phtml(76): view()
#9 …/app/View.php(183): include('...')
#10 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#11 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#12 …/app/Http/ViewResponseTrait.php(54): view()
#13 …/app/Http/RequestHandlers/TreePage.php(87): Fisharebest\Webtrees\Http\RequestHandlers\TreePage->viewResponse()
![temp](https://user-images.githubusercontent.com/5910274/209255323-a635f267-07ed-4b29-a5c1-3d69b4b3b2ab.jpg)

**Comment by WGroleau** [comment]
If I switch to that tree by editing the URI, I get the same crash.  That is in Safari.  In Firefox, I get that crash if I go directly to that tree's URI from a different domain name.  So there is something in that tree that a module doesn't like but which does not show in "check for errors"

**Comment by WGroleau** [comment]
I tried to send additional info that should not be put here, but your contact form failed.

**Comment by JustCarmen** [comment]
> I tried to send additional info that should not be put here, but your contact form failed

Probably a temporary glitch because I just tested it and have no problems.
But you can also find my email in my profile here on Github or in my profile on webtrees.

> Call to a member function canShow() on null …/modules_v4/jc-fancy-treeview/FancyTreeviewModule.php:417

Are you using the latest beta version?

**Comment by WGroleau** [comment]
Today, updated webtrees and Vesta.  This error still occurs.  Odd that it only happens on the small tree.

**Comment by WGroleau** [comment]
And then, I saw that there has been a change since my last download.  Installed the latest fancy-treeview without changing any of your other modules.  The crash is fixed.
