### ISSUE TITLE
feature request : possibility to display note 

### ISSUE THREAD

**Issue by Fa10175** [JustCarmen/webtrees-fancy-treeview#112]
in the future, having the ability to view the notes would be a plus 
I know it's a lot of work.
thank you

**Comment by JustCarmen** [comment]
What kind of notes are you talking about?

There are level 1, 2 and 3 notes
There are inline notes and shared notes

Some notes can contain quite a lot of text. I am not sure if we want those on the Fancy Treeview page (or tab).

**Comment by Fa10175** [comment]
the notes I would like to see would be "inline notes".
Some notes can contain quite a lot of text, this is true.

the consultation for me would be only on the screen.
 
see
![Screenshot 2022-12-27 at 10-59-17 King George V 1865–1936 – webtrees](https://user-images.githubusercontent.com/10681601/209649546-a6ea6b36-30d8-4db3-8cee-b691c04cb4bc.png)

**Comment by Fa10175** [comment]
I just tested this locally.
It works well for me.
Great
thanks

**Comment by Fa10175** [comment]
just for your information adding the notes is correct but in this version of the file "at the age of" is not translate

if I replace 
near line 1388 

       $html     = '';
        if ($bdate->isOK() && $ddate->isOK() && $this->isDateDMY($bfact) && $this->isDateDMY($dfact)) {
            $ageAtDeath = new Age($bdate, $ddate);
            $html .= ' ' . /* I18N: %s is a string e.g. 2 days/months/years */ I18N::translate('at the age of %s', $ageAtDeath);
        }
        return $html;


by

        if ($bdate->isOK() && $ddate->isOK() && $this->isDateDMY($bfact) && $this->isDateDMY($dfact)) {
            $ageAtDeath = (string) new Age($bdate, $ddate);
            if ($ageAtDeath < 2) {
                $html .= ' ' . /* I18N: %s is the age of death in days/months; %s is a string, e.g. at the age of 2 months */ I18N::translateContext('age in days/months', 'at the age of %s', $ageAtDeath);
            } else {
                $html .= ' ' . /* I18N: %s is the age of death in years; %s is a number, e.g. at the age of 40. If necessary add the term 'years' (always plural) to the string */ I18N::translateContext('age in years', 'at the age of %s', filter_var($ageAtDeath, FILTER_SANITIZE_NUMBER_INT));
            }
        }
        return $html;
it's ok

**Comment by JustCarmen** [comment]
This is caused by commit #117. I've fixed a bug regarding age calculation. Due to this change a new language string is introduced. I haven't updated the language files yet, so that is why you see an untranslated string.
