### ISSUE TITLE
strange behaviour of font size on android pad

### ISSUE THREAD

**Issue by LarsRabe** [JustCarmen/webtrees-fancy-treeview#113]
Hello Carmen,

on my android pad using it in landscape orientation the font size behaves strangly:
![font-size](https://user-images.githubusercontent.com/119816325/210396278-919f851d-f1e6-4fb9-8df9-b35c746a9b51.jpg)
In this screenshot from my computer all the lines have the same font size (as it should be). What happens on my android device using the landscape orienation is, that all the lines, apart from the first one, are showing a **larger** font size. If I manually scroll down, the font size of all lines normalize to normal font size. The same effect is also there, when I use the "follow x.x" link (not scrolling down). It does NOT happen holding my pad in portrait orientation.

Do you have a explanation?

**Comment by JustCarmen** [comment]
I cannot reproduce this. Is it possible that the page wasn't fully loaded?

**Comment by LarsRabe** [comment]
> I cannot reproduce this. Is it possible that the page wasn't fully loaded?
It looks like it was fully uploaded. I can reproduce this on 3 different pads, but not on android phones in landscape orientation.

Don't get it either

**Comment by JustCarmen** [comment]
Can you place a screenshot of the issue?

**Comment by LarsRabe** [comment]
Hi Carmen,

Two screenshots. As you can see, the first line (sentence) hat a normal font size. The next lines (sentences) do have a larger font size.
![Screenshot_20230108_141832_com android chrome](https://user-images.githubusercontent.com/119816325/211198484-fe391368-7c24-4593-9f16-4b08bfb07497.jpg)

![Screenshot_20230108_142002_com android chrome](https://user-images.githubusercontent.com/119816325/211198583-6f5f2f07-36ad-4216-80de-53651c9e9fdc.jpg)

**Comment by JustCarmen** [comment]
I've looked into this once again, but I can't think of anything that can cause this behavior. I don't use a special font size in the module. All text is wrapped in a paragraph tag, but that also counts for the first paragraph which is not enlarged. 

Can you reproduce this behavior with the webtrees theme? If you disable all custom modules, except Fancy Treeview of course, do you have the same situation?

**Comment by LarsRabe** [comment]
Hello Carmen, it's the same if I use the webtrees theme. Also disabling custom modules doesn't change anything. And  of course I deleted the browser cache on trying. :-) I try 2 other tablets and a ipad tomorrow at work. The 3 tablets in my household all show this behaviour. In addition I'll try some other browsers too.

**Comment by JustCarmen** [comment]
I might have found something:

https://kilianvalkhof.com/2022/css-html/your-css-reset-needs-text-size-adjust-probably/

https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust

I still cannot reproduce it on my own Android tablet, also tried a Chromebook and a mobile device simulator without any luck.

So I need your help to solve this. Would you please add the following css to the upper textblock of the css-and-js module:

`<style> 
html {
  -moz-text-size-adjust: none;
  -webkit-text-size-adjust: none;
  text-size-adjust: none;
}
</style>`

Let me know if it makes any difference.

**Comment by LarsRabe** [comment]
I think you're on something there. Initially it seems to have no effect, but...
now, if I scroll down, after a short moment the font size adapts to the right size. So it definitely changed the behaviour. 

I'm not 100 % sure it's the scrolling down. It seems sometimes if tapping on the tablet triggers it also.

Further more I tested a ipad today. There the behaviour doesn't show. On two other android tablets at work, the behaviour is showing as on my household tablets. In all cases I was using the Chrome browser.

**Comment by LarsRabe** [comment]
Since version 2.0.5 this behaviour no longer exist.😀
