### ISSUE TITLE
renaming the install folder breaks the module

### ISSUE THREAD

**Issue by LarsRabe** [JustCarmen/webtrees-fancy-treeview#115]
Hello Carmen,
referring to #114 

I know I'm a bit mean now, but as discussed here https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/37615-most-efficient-way-to-add-a-media-object-with-source-and-source-citation?start=20 renaming the install folder **should not break** the module. As I tried the statement of @ric2015 on that with your module, it shows that hardcoding leads to not functioning of your module if a user renames the install folder.

I think your solution sadly isn't the golden solution. You might rethink that?

**Comment by LarsRabe** [comment]
After a bit more testing the only problem seems to be that the top menu (with the views) is no longer visible.

**Comment by JustCarmen** [comment]
Exactly. The module doesn't break, which is good.

But the module options are saved in the database with the module name in the module settings table. I guess this name should be fixed in stead of depending on the directory name.

**Comment by JustCarmen** [comment]
But on reflection, this webtrees by default. I use the built-in functions $this->setPreference() and $this->getPreference(). Those functions refer to the internal module name $this->name() which is derived from the module folder name. Since these are native webtrees functions, I think you should submit your problem there.

**Comment by JustCarmen** [comment]
But I am wondering, why would you rename the folder?

**Comment by LarsRabe** [comment]
> But I am wondering, why would you rename the folder?

a) I was triggered by the forum discussion to try this because of the routing problem. I would see if the hardcoding has a effect. :)
b) From experience: user do things that the programmer even didn't think of they would do that.

But you gave the hint `$this->name()` etc. So you're right, that the foolproof has to come from Greg.
