### ISSUE TITLE
Request: increase maximum number of generations per page / per tab

### ISSUE THREAD

**Issue by reteP-riS** [JustCarmen/webtrees-fancy-treeview#116]
First of all THANKS for this great module!

I tested performance extensively by increasing the maximum number of generations up to 12 in the following lines, even activating the _Show singles_ option and the _Check relationship between partners_ option in situations where I do have pedigree collapses. Your module works like a charm with lightning speed. Kudos!
https://github.com/JustCarmen/webtrees-fancy-treeview/blob/f81bd476f8377aa5da314aa03bd5a4ba72577464/resources/views/settings.phtml#L37
https://github.com/JustCarmen/webtrees-fancy-treeview/blob/f81bd476f8377aa5da314aa03bd5a4ba72577464/resources/views/settings.phtml#L53

I cannot see any performance degradation and therefore request to increase the maximum number of generations to at least 10 or even 20 and leave it to the webtrees admins to set these limits responsibly for their specific situation.

**Comment by JustCarmen** [comment]
Nice to hear that the module works well and without performance issues. I will take this on board for the next release.
