### ISSUE TITLE
Age at death in days/months inaccurately shown in years

### ISSUE THREAD

**Issue by MarkyJ1** [JustCarmen/webtrees-fancy-treeview#117]
Function: `printAgeAtDeath`

When checking age at death - `if ($ageAtDeath < 2)` - those ages calculated in days or months (not years) will only be correctly shown when less than 2 days or 2 months.

e.g.

An age at death of '1 day' will be correctly shown as '1 day'.
An age at death of '3 days' will be incorrectly shown as '3' (years implied and filtered out).

The current check doesn't care if the age is in days, months or years so maybe instead just check if the string `$ageAtDeath` does not contain the text 'year'.

Replace: `if ($ageAtDeath < 2)`
With: `if (!str_contains($ageAtDeath, 'year'))`  - php 8 needed!

**Comment by JustCarmen** [comment]
You're right, some changes have been made to the Webtrees Age function that make the current calculation incorrect.
