### ISSUE TITLE
Age at death not calculated when date qualifiers used

### ISSUE THREAD

**Issue by MarkyJ1** [JustCarmen/webtrees-fancy-treeview#118]
This is a consideration / possible enhancement.

When date qualifiers exist for a birth and/or death date the function `isDateDMY` correctly returns FALSE and no age at death is calculated and displayed for those individuals that have both birth and death dates, at least one of which contains a date qualifier.

To be consistent with core webtrees functionality it is better for the function `printAgeAtDeath` to still calculate the age at death and perhaps add a qualifier such as 'about' or 'approximately'.

e.g.

....... died between January 1920 and March 1920 at the age of about 78.

**Comment by JustCarmen** [comment]
That would be nice indeed. I'll see what I can do.
