### ISSUE TITLE
Module not translated in French

### ISSUE THREAD

**Issue by oklotz31** [JustCarmen/webtrees-fancy-treeview#120]
The module runs correctly but stays in English when French is selected.  Except for "soon" and "daughter" that are translated in French.
The rest of the site switches correctly in the selected language.
All lang files are in the "lang" directory of the module.
I checked translations in poeditor and is 100% for French.
Version of Webtrees is 2.1.15

**Comment by JustCarmen** [comment]
I cannot reproduce this. The module is translated in French and it is working as expected.

Have you downloaded [the release version](https://github.com/JustCarmen/webtrees-fancy-treeview/releases/latest) with the compiled language files? Does the file fr.mo exist in the folder resources/lang? I suspect you have downloaded the source code which doesn't contain the compiled language files.

**Comment by oklotz31** [comment]
Hello
I reload the module from your link, instead of from the "<> Code" menu from the main page. And it works. 

Thanks for your support.
