### ISSUE TITLE
Using tree favorites instead of menu items

### ISSUE THREAD

**Issue by hartenthaler** [JustCarmen/webtrees-fancy-treeview#121]
At the moment your module generates new menu items when storing a favorite report. The space for menu topics is limited (better: it does not look nice if there are too many menu topics). So I would prefer to add new reports as URL in webtrees "tree favorites" instead of using this additional menu topic. Or let the admin decide which function is preferred (there are side effects regarding visibility for visitors for example).

**Comment by JustCarmen** [comment]
Nice idea. I'll see what I can do.

**Comment by JustCarmen** [comment]
In stead of using the favorites module, I decided to create a separate homepage block with an overview of links to Fancy Treeview pages. I think this will also serve your needs.

**Comment by hartenthaler** [comment]
This idea is great! I like the new html-block. I prefer now a new option in the control panel of your module to switch off the main menu item.

**Comment by JustCarmen** [comment]
> This idea is great! I like the new html-block. 

Glad you like it :)

> I prefer now a new option in the control panel of your module to switch off the main menu item.

This is not necessary. You can go to control panel / menus and change the access level of the Fancy Treeview menu to 'Hide from everyone'.

**Comment by hartenthaler** [comment]
perfect!
