### ISSUE TITLE
Fancy-Treeview Translation

### ISSUE THREAD

**Issue by gudjonsi** [JustCarmen/webtrees-fancy-treeview#122]
Not sure if I should address an issue with translation of fancy-treeview here, but I'm unable to locate the sentence "Children of" in the fancy-treeview language file (poeditor.com). There is no sentence with "Children of" in the fancy-treeview language file but in the webtrees language file I was able to locate this sentence but despite my effort to change it in the webtrees language file the change is not reflected in fancy-treeview (downloaded a new webtrees language file with the correction and installed it in the specific webtrees language folder as .po file and then deleted the old messages.php file). The correction is reflected in webtrees but not in the fancy-treeview mod. Can you point me to the correct location of this translation string? I've tried clearing the browser cache and also tried different browsers without any luck.

Thank you for providing and maintaining all your great mods for webtrees.

![Image 3 2 2023 at 17 09](https://user-images.githubusercontent.com/100283838/216668211-30a81e19-916b-493d-bb76-f5a86179e162.jpeg)

**Comment by JustCarmen** [comment]
In the code Children of were two separate strings. Probably a leftover from version 1. I've now combined the strings as "Children of " which string exists as combined string in the webtrees language files.

Strings that exist in webtrees are not in the Fancy Treeview translation files to prevent deviating translations.

If you want to use a modified translation immediately without waiting for a new version you need the compiled mo-files which you can download from the translation server.

**Comment by gudjonsi** [comment]
Great, thanks for solving this.
