### ISSUE TITLE
abbreviate place names

### ISSUE THREAD

**Issue by ghezibde** [JustCarmen/webtrees-fancy-treeview#124]
Thanks for this great module !
Whole hierarchy of place names are used in report, i'd prefer place names were abbreviated as set up in General Control Panel as show here
![image](https://user-images.githubusercontent.com/75539399/218090035-95386c4a-31b5-430d-91ad-6c5277e072f8.png)
Would that be possible ?

**Comment by ghezibde** [comment]
excuse me, already issued  in #77

**Comment by JustCarmen** [comment]
Closed due to duplicate.
