### ISSUE TITLE
Request: more options for display place names

### ISSUE THREAD

**Issue by TheDutchJewel** [JustCarmen/webtrees-fancy-treeview#129]
Thanks for the new [display of place names](https://github.com/JustCarmen/webtrees-fancy-treeview/commit/cdb7a4453fd1a270a7f485a058625604d69f48a9).

I like to see two more options:

1. lowest level in home country with full place names in other countries:
`Zuidzande, Zeeuws-Vlaanderen, Zeeland, Nederland` -> `Zuidzande`

2. lowest and second-highest level in home country with full place names in other countries:
`Zuidzande, Zeeuws-Vlaanderen, Zeeland, Nederland` ->` Zuidzande, Zeeland`

Is that possible?

**Comment by JustCarmen** [comment]
I think it gets very complicated that way. Currently, I am not eager to add more options to display place names.
