### ISSUE TITLE
Polish the output by using ChatGPT

### ISSUE THREAD

**Issue by hartenthaler** [JustCarmen/webtrees-fancy-treeview#130]
I like your module very much, but the narrative style is a bit "hölzern" (I don't know a good translation into English). I just checked what happens if I use the output of your module and prompt ChatGPT to polish it. Impressive but not perfect. Maybe it would be an enhancement for your module if you use the OpenAI API to get better-styled text.

**Comment by hartenthaler** [comment]
see
- https://discourse.genealogy.net/t/chatgpt-spricht-gedcom-revolutionaere-moeglichkeiten-fuer-die-genealogie/815266
- https://aweekofgenealogy.com/chatgpt-and-gedcom-files/

**Comment by JustCarmen** [comment]
I've used chatGPT a few times to rewrite some texts and the results are pretty impressive, but certainly not perfect.

It looks like an easy solution, but it takes a lot of work to implement the texts rewritten by chatGPT into the code and translations.

**Comment by hartenthaler** [comment]
It would not be necessary to translate anything - if I'm right. Use the already translated text that was generated by your module and ask ChatGPT to optimize it. Then ChatGPT should do this in the same language as it is desired. 

Or build some GEDCOM code that contains exactly what you like to have in the report. Then prompt ChatGPT: use this GEDCOM to build a narrative story in xxx language. 

This is all very experimental, maybe up to now not ready for a productive system.

**Comment by JustCarmen** [comment]
I'm afraid I don't quite understand you. Texts are generated with PHP code in the module. I can ask chatGPT to optimise these texts, but ultimately these texts need to be replaced with the texts suggested by chatGPT so that they can be displayed to site visitors.

**Comment by hartenthaler** [comment]
Yes, indeed. Take the text generated by your module (for example in German), send it via the OpenAI web service to ChatGPT and prompt that service to optimize the text. Then display in your module the returned optimized text instead of the original text.

But again, maybe this is a more experimental approach. But in my trials, the text, which was optimized by ChatGPT was better readable than the original one.

**Comment by JustCarmen** [comment]
I have decided not to investigate this further or to implement this into the module. A ChatGPT api key is not free of charge. So every user should obtain their own api key, which is not very user friendly.

Therefore I'll close this issue.
