### ISSUE TITLE
 May I ask how to add language and provide a thought process? 

### ISSUE THREAD

**Issue by kexuebin** [JustCarmen/webtrees-fancy-treeview#134]
May I ask how to add language and provide a thought process? I want to provide translation language, but I don't know how to start

**Comment by JustCarmen** [comment]
You can start here: https://poeditor.com/join/project/9HqYANIknp

Thanks in advance.

**Comment by kexuebin** [comment]
> You can start here: https://poeditor.com/join/project/9HqYANIknp
> 
> Thanks in advance.

Translated already
