### ISSUE TITLE
Doubling of generations in the descendant view

### ISSUE THREAD

**Issue by heiler** [JustCarmen/webtrees-fancy-treeview#137]
In this example of my page [heiler-ahnen.de](https://www.heiler-ahnen.de) in the descendant view the persons from the 2nd generation appear again in the 4th generation.
 This refers to version 2.0.3

![Bildschirmfoto vom 2023-10-19 11-17-15](https://github.com/JustCarmen/webtrees-fancy-treeview/assets/2920260/22072552-b008-491f-a978-b1dc9622f39d)
![Bildschirmfoto vom 2023-10-19 11-17-51](https://github.com/JustCarmen/webtrees-fancy-treeview/assets/2920260/8aa82d99-225b-4fb0-a48b-54f816307325)

**Comment by JustCarmen** [comment]
I was able to reproduce this. I don't know how it can be that I didn't see this before the release.... but, anyway, I need to fix this. I don't have much time today, but I will probably be able to dive into this issue this weekend. I suspect it has something to do with commit https://github.com/JustCarmen/webtrees-fancy-treeview/commit/6fee9c2b7078b410022470e249dbaf34a854b6e4.
