### ISSUE TITLE
Ugly page breaks when printing

### ISSUE THREAD

**Issue by reteP-riS** [JustCarmen/webtrees-fancy-treeview#139]
When printing ancestors or descendants from this module ugly page breaks occur every now and then. Sometimes writing and even photos are split over two pages.

Any idea how to fix this, maybe with page-break-inside:avoid?

![UglyPageBreaks](https://github.com/JustCarmen/webtrees-fancy-treeview/assets/77232439/cf2f3f81-9e1b-4c3d-bd59-85cce25d518e)

**Comment by reteP-riS** [comment]
I just installed the latest Fancy TreeView release v2.0.5 on top of webtrees v2.1.20. The printout looks perfect with the latest version of MS Edge Version v125.0.2535.67. That's really nice - thanks!
Unfortunatly the fixes don't seem to work with the latest version of Firefox v126.0. Although I can see the CSS changes break-after:avoid, break-before:avoid and break-inside:avoid with the developer tools they don't have the intended effect.

**Comment by JustCarmen** [comment]
I see what you mean. I need to dive into this. I'll reopen this issue.

**Comment by JustCarmen** [comment]
It seems that Firefox has some bugs with print style rules. That's why I can't get it to work. 

So my advice would be to use MS Edge or Chrome when printing a Fancy Treeview page.
