### ISSUE TITLE
No spouse printed when "MARR" tag is absent

### ISSUE THREAD

**Issue by BertKoor** [JustCarmen/webtrees-fancy-treeview#140]
Follow up on forum topic https://www.webtrees.net/index.php/forum/help-for-release-2-1-x/38512-hi-regarding-the-problem-of-displaying-the-wife-in-the-fancy-treeview-module#102745

When no family has a MARR tag, then $spousecount remains zero and thus the details of the partner(s) are not printed.

A spouse will be printed when either "MARR N" is present or another family with "MARR Y" exists, so it looks like an oversight.

**Comment by MarkyJ1** [comment]
Also, in function **printPartner**, lifespan details will only be shown if a **_NMR** (not married) tag exists. I don't think that this check is needed.

**Comment by xiaoyang2013** [comment]
Thank you for your attention to this issue

**Comment by JustCarmen** [comment]
Thanks for this notification and the offered solutions. I think this will work.
