### ISSUE TITLE
Job is written in non-captal letters

### ISSUE THREAD

**Issue by WeT-Klb** [JustCarmen/webtrees-fancy-treeview#141]
In your module the job´s name will be changed to non-capital initial letter.
I added pics from the facts tab and of your module descrption.
![Pic 1](https://github.com/JustCarmen/webtrees-fancy-treeview/assets/20600342/d7ea3ebd-0057-466a-b4f2-6c475d345b03)
![Pic 2](https://github.com/JustCarmen/webtrees-fancy-treeview/assets/20600342/adc8fd82-7b95-483f-baba-5d4821b5b55b)

**Comment by ungeahnt** [comment]
The “treeview/occupation“ setting 

“Always write the occupation exactly as it appears in the Gedcom“ = Yes 

should do it.

former discussion see #93

**Comment by WeT-Klb** [comment]
Ah -yes, Now it is shown like it should be. Thanks so much.
