### ISSUE TITLE
Homepage Block isn't working

### ISSUE THREAD

**Issue by manf0001** [JustCarmen/webtrees-fancy-treeview#142]
Hello,  When I apply the Fancy Treeview to the Home Page as a block, it shows nothing, is there an option in the plugin settings?  I didn't see anything in there?    I also set a Default ancestor for the tree to, thinking that might help, but it didn't change anything.

I'm using webtrees 2.1.18  and The Fancy Treeview Plugin is 2.0.4

Thanks

![homepage block](https://github.com/JustCarmen/webtrees-fancy-treeview/assets/77053842/8c74b4d2-7262-49f8-bef4-613562d403f2)
![homepage](https://github.com/JustCarmen/webtrees-fancy-treeview/assets/77053842/0d86aa5a-1adb-4f1b-ae6f-b22c631766cf)

**Comment by JustCarmen** [comment]
I agree, this is not very intuitive.

When you are on a Fancy Treeview page you'll see a link at the top of the page:  Create link to this page.
You can also create a link from the edit menu on the individual page.

The links will be included in the homepage block.

But I agree with you, if you are a new user than it is not very clear how to fill the block. A help text should fix that.
