### ISSUE TITLE
Print options (feature request)

### ISSUE THREAD

**Issue by WGroleau** [JustCarmen/webtrees-fancy-treeview#143]
It would be nice to have a print option in CSS or some other way of printing just the tab contents without the webtrees headers, footers, and sidebar.

It would also be nice to be able to restrict ability to print to certain user roles.

**Comment by JustCarmen** [comment]
You already can print out the page without headers etc. Just click ctrl. P (default browser option) to print the page.

You have to do this from the full page, not from the individual page. The annoying thing, though, is that you can only print the current page. So if you want to print all generations, you have to set the 'Maximum number of generations per page' to the highest level. This may affect the page load time.

The screenshot below shows what the page to be printed (or saved as pdf) looks like.

![image](https://github.com/JustCarmen/webtrees-fancy-treeview/assets/5641963/cd265c40-4add-47e3-b6ac-98c491945b5d)

**Comment by WGroleau** [comment]
I do not understand "full page" vs. "individual page"

**Comment by JustCarmen** [comment]
Example from my own website:

Tab individual page: https://wijzijnfamilie.nl/tree/wijzijnfamilie/individual/I3326/Johan-George-Honig#tab-_jc-fancy-treeview_

Same person from the full fancy treeview page (click the read more link or create a link):

https://wijzijnfamilie.nl/tree/wijzijnfamilie/jc-fancy-treeview/I3326/johan-george-honig/descendants/1

I should provide a better explanation in the readme file. Apparently the functions of the module are not very clear.

**Comment by WGroleau** [comment]
Makes sense.  I was expecting the "read more" to be a "page two" which is actually what it did.  But at the end of the URI was `/2#6` and when I changed that to `/1`, I got the first five generations, with paging controls at the bottom.  Printing from this format gives fewer pages than printing with the sidebars.
