### ISSUE TITLE
Block "Fancy-Treeview"

### ISSUE THREAD

**Issue by hartenthaler** [JustCarmen/webtrees-fancy-treeview#146]
A block  "Fancy-Treeview" is available for the my-page/tree starting page. But it is always empty and I didn't find a possibility to specify the content of that block.

**Comment by JustCarmen** [comment]
See: https://github.com/JustCarmen/webtrees-fancy-treeview/issues/142

I've added a help text to make clear how to use the block.
I'll draft a new release soon.

**Comment by JustCarmen** [comment]
I've just released the new version which contains the block help text.

https://github.com/JustCarmen/webtrees-fancy-treeview/releases/latest
