### ISSUE TITLE
Indication of birth in different tenses

### ISSUE THREAD

**Issue by WeT-Klb** [JustCarmen/webtrees-fancy-treeview#147]
Mir ist aufgefallen, dass im Deutschen die Geburt aller Männer in der Vergangenheitsform angegeben wird, teilweise die der Frauen aber in der Gegenwarts- oder Zukunftsform, so dass es bei Männern "wurde geboren" heißt, bei Frauen aber "wird geboren".
Aufgefallen ist es mir vor allem bei Frauen, denen ich 2 Geburtsnamen (einmal Deutsch, einmal Chinesisch) zugewiesen habe.

I have noticed that in German the birth of all men is given in the past tense, but sometimes the birth of women is given in the present or future tense, so that for men it is "wurde geboren (was born)", but for women it is "wird geboren (is born)".
I have noticed this especially with women to whom I have assigned 2 birth names (one German, one Chinese).

**Comment by JustCarmen** [comment]
This is a matter of translation.

I usually don't do the translations myself. There are many native speakers contributing. But I do notice a difference between the male and female translation of 'was born' when the context is the present.

I think the male version should be translated as 'wird geboren'. Am I right?

![image](https://github.com/JustCarmen/webtrees-fancy-treeview/assets/5641963/282d7b29-c896-487c-a0ea-1101b1212860)

**Comment by WeT-Klb** [comment]
First of all both should be the same. And as the birth has already happened i think was born (wurde geboren) would be the better choice.
And it seems like there is a difference between living and died women.
In my initial post I was wrong - it doesn't matter if the women have a second birth name assigned.
If they are still live your plugin will show "is born" - like it is happening right now.
If the women already died your plugin will show "wurde geboren" - the past form.
So under the line for both, **male and female**, there always should be used "**wurde geboren**" in german translation.
The translation of "wird geboren" is "is born" - that sounds weired.

**Comment by mpwt** [comment]
Ich habe mir aufgrund der Diskussion erlaubt, heute Nachmittag die Übersetzung zu vereinheitlichen. Alle past-Versionen sind mit "wurde" und alle present-Versionen sind nun mit "ist". Damit ist es für männlich und weiblich gleich.

Die Form "wird" wäre future. 

Interessanterweise ist die englische Ausgangsform in past und present immer "was" ...

**Comment by WeT-Klb** [comment]
Was auch seltsam klingt: Wenn man bei einer verheirateten Frau nachschaut, steht z.B. auch, wann sie geheiratet haben - allerdings auch in der Gegenwartsform. Auch hier wäre die Vergangenheitsform passender.

**Comment by mpwt** [comment]
Probiere mal diese geänderte Datei aus. Dazu bitte entpacken als de.mo und in den Ordner modules_v4/jc-fancy-treeview/resources/lang/ hochladen. Ich habe überalle "wurde" daraus gemacht und die mehrfachen Heraten angepasst.

[de.mo.zip](https://github.com/JustCarmen/webtrees-fancy-treeview/files/15370724/de.mo.zip)

**Comment by WeT-Klb** [comment]
> Probiere mal diese geänderte Datei aus. Dazu bitte entpacken als de.mo und in den Ordner modules_v4/jc-fancy-treeview/resources/lang/ hochladen. Ich habe überall "wurde" daraus gemacht und die mehrfachen Heiraten angepasst.
> 
> [de.mo.zip](https://github.com/JustCarmen/webtrees-fancy-treeview/files/15370724/de.mo.zip)

Super, daß sieht gut ist. Vielen Dank für die neue Übersetzung.
