### ISSUE TITLE
ontbrekende geboortedata

### ISSUE THREAD

**Issue by mariannevanharten** [JustCarmen/webtrees-fancy-treeview#148]
In het overzicht dat door deze mooie module wordt gemaakt, ontbreekt van de jongste generatie de geboortedatum en -plaats.

**Comment by JustCarmen** [comment]
Je moet in de optie 'toon alleenstaanden' op ja zetten om de volledige details te zien van personen zonder partner of kinderen. Anders worden kinderen alleen in de lijst bij de gegevens van de ouders genoemd.

**Comment by mariannevanharten** [comment]
Dankjewel. Die optie had ik over het hoofd gezien.
Ik ben blij met deze module!

Groetjes,
Marianne
