### ISSUE TITLE
verleden tijd bij relatie?

### ISSUE THREAD

**Issue by mariannevanharten** [JustCarmen/webtrees-fancy-treeview#149]
Bij een huwelijk van twee personen staat: "Zij trouwde met ... op ...". Hier is gebruik van de verleden tijd niet verkeerd.
Bij een (nog actuele) relatie van twee personen staat "Zij had een relatie met ...". Hier is gebruik van de verleden tijd niet juist, omdat de relatie nog steeds bestaat.

**Comment by JustCarmen** [comment]
Je hebt gelijk. Ik ga kijken of ik dat kan verbeteren.

**Comment by mariannevanharten** [comment]
Tip: "Ging een relatie aan met"...
Daarmee laat je in het midden of de relatie al dan niet nog steeds bestaat.
