### ISSUE TITLE
Treeviw Block - German translation not working

### ISSUE THREAD

**Issue by HerzScheisse** [JustCarmen/webtrees-fancy-treeview#151]
Hi,

I noticed that the translations on the empty fancy treeview block are not translated from english to german...

But the translations are in the de.po file... Do you have a idea what can cause this?

running on webtress 2.1.20 with latest fancy treeview module

![treeviw translation](https://github.com/user-attachments/assets/1621306c-81d2-4d4e-860f-87881aa559d7)

**Comment by JustCarmen** [comment]
On the translation server the translated strings for this block were marked as 'fuzzy'. This means the translations need to be reviewed by someone else. Thus they are still in process and therefore not added to the compiled *.mo files.

I've removed the fuzzy restriction now, so these strings will part of the final translation. Adjustments can be made later anyway.

The compiled mo file will be part of the next release.

**Comment by HerzScheisse** [comment]
> This means the translations need to be reviewed by someone else

Oh, okay... i have seen this sometimes in the past, but didnt know what it means... so thank you for explanaition and the fixes...
