### ISSUE TITLE
Fehler in deutscher Übersetzung in Version 2.1.0

### ISSUE THREAD

**Issue by WeT-Klb** [JustCarmen/webtrees-fancy-treeview#154]
Hallo, in der deutschen Übersetzung hat sich ein Fehler eingeschlichen. Wenn der Beruf zusammen mit dem Arbeitgeber angezeigt wird, schreibt Treeview "mit" anstatt "bei". Kann das berichtigt werden? Screenshots habe ich angefügt.

Hello, an error has crept into the German translation. If the profession is displayed together with the employer, Treeview writes ‘mit’ instead of ‘bei’. Can this be corrected? I have attached screenshots.
![Berufe](https://github.com/user-attachments/assets/be0dcad4-f522-4312-81e4-47d45e8d50a6)
![Treeview 1](https://github.com/user-attachments/assets/0a8f947b-dfbe-4192-b2eb-3d9d9d43d736)

**Comment by mpwt** [comment]
I have change the translation of „with“ from „mit“ to „bei“.

**Comment by WeT-Klb** [comment]
Thanks so much. Can you tell me where I can find that update? What`s the file`s name?

**Comment by mpwt** [comment]
You have to wait until Carmen imports the changed language file. But you can also make the change yourself until then: In the add-on directory go to the subfolder resouces > lang to the file de.po and change it with an editor for the part “mit” to “bei” and upload it again to the same place.

**Comment by JustCarmen** [comment]
To use the translated file on your website you need the compiled mo file. It will be added to the next release, but for your convenience you can download it right now from here.

Unzip the file in the folder resources/lang inside the fancytreeview folder.

[de.zip](https://github.com/user-attachments/files/18130049/de.zip)

**Comment by WeT-Klb** [comment]
Thanks so much for your service - it works perfectly.
