### ISSUE TITLE
Relationships between individual and spouse

### ISSUE THREAD

**Issue by tronsmit** [JustCarmen/webtrees-fancy-treeview#51]
(Feature request)

Would it be possible to include 'only search through ancestors' as a configurable option? (fourth parameter in the calculateRelationships() function call).

This would exclude links by marriage and be true blood relationships.

**Comment by JustCarmen** [comment]
Hi I agree with you this should be made possible now this feature is implemented in webtrees. I have to dive into the code to see how to use it, but I'll figure it out. I'll put this on my todo list.

**Comment by JustCarmen** [comment]
After more than 4 years I've released a new version of the module for webtrees 2. At the moment it is in beta state but I encourage you to try it out.

I will close all old issues. But if you think this issue still stands you can re-open this issue or create a new one.
