### ISSUE TITLE
Matriline/patriline report

### ISSUE THREAD

**Issue by HRN-webtrees** [JustCarmen/webtrees-fancy-treeview#57]
For tracing matrilines (mtDNA) and patrilines (Y DNA) from a given individual, I would love to see a report similar to fancy_treeview.
JustCarmen, any chance this module could be rewritten for this purpose i.e allowing us to choose female or male descendancy only?

**Comment by curtisdelicata** [comment]
👍

**Comment by JustCarmen** [comment]
After more than 4 years I've released a new version of the module for webtrees 2. At the moment it is in beta state but I encourage you to try it out.

I will close all old issues. But if you think this issue still stands you can re-open this issue or create a new one.
