### ISSUE TITLE
In webtrees 2.0.0 I cannot configure Fancy Treeview

### ISSUE THREAD

**Issue by melizaa** [JustCarmen/webtrees-fancy-treeview#58]
In webrteees 2.0.0 when I try to configure Fancy Treevies on my test site, I get 
This www.amitys.com page can’t be found

No webpage was found for the web address: https://www.amitys.com/test/module.php?mod=fancy_treeview&amp;mod_action=admin_config
HTTP ERROR 404

**Comment by JustCarmen** [comment]
After more than 4 years I've released a new version of the module for webtrees 2. At the moment it is in beta state but I encourage you to try it out.

I will close all old issues. But if you think this issue still stands you can re-open this issue or create a new one.
