### ISSUE TITLE
Fancy Treeview PDF seems not to work in webtrees 2.0.0

### ISSUE THREAD

**Issue by melizaa** [JustCarmen/webtrees-fancy-treeview#59]
I have uploaded the Fancy Treeview PDF files to my webtrees 2.0.0. test site. I have added mpdf files. I do not see Fancy Treeview PDF in the module administrator page.

Where do I err?

**Comment by JustCarmen** [comment]
After more than 4 years I've released a new version of the module for webtrees 2. At the moment it is in beta state but I encourage you to try it out.

I will close all old issues. But if you think this issue still stands you can re-open this issue or create a new one.
