### ISSUE TITLE
Fancy Treeview pictures on rtl pages - webtrees 2.0.0

### ISSUE THREAD

**Issue by melizaa** [JustCarmen/webtrees-fancy-treeview#60]
I do not see spaces between pictures and text on rtl Fancy TreeView pages.
Perhaps the spaces print to the right of the pictures instead of the left?
![2017-11-16_13-43-39](https://user-images.githubusercontent.com/5202996/32889600-32c3dfa6-cad4-11e7-8a3f-50c7a3a10016.jpg)

**Comment by JustCarmen** [comment]
After more than 4 years I've released a new version of the module for webtrees 2. At the moment it is in beta state but I encourage you to try it out.

I will close all old issues. But if you think this issue still stands you can re-open this issue or create a new one.
