### ISSUE TITLE
Error on tree view

### ISSUE THREAD

**Issue by curtisdelicata** [JustCarmen/webtrees-fancy-treeview#62]
See error below when viewing the link provided after configuring root person.

/home/curtis/public_html/modules_v3/fancy_treeview/app/FancyTreeviewClass.php:956 Call to undefined method Fisharebest\Webtrees\Individual::findHighlightedMedia() #0 /modules_v3/fancy_treeview/app/FancyTreeviewClass.php:466 Error("Call to undefined method Fisharebest\Webtrees\Individual::findHighlightedMedia()") #1 /modules_v3/fancy_treeview/app/FancyTreeviewClass.php:411 printIndividual([Individual I16877@2]) #2 /modules_v3/fancy_treeview/app/FancyTreeviewClass.php:371 printBlockContent() #3 /modules_v3/fancy_treeview/app/FancyTreeviewClass.php:313 printGeneration() #4 /modules_v3/fancy_treeview/app/Template/PageTemplate.php:111 printPage() #5 /modules_v3/fancy_treeview/app/Template/PageTemplate.php:92 pageBodyContent() #6 /modules_v3/fancy_treeview/app/Template/PageTemplate.php:35 pageBody([PageController]) #7 /modules_v3/fancy_treeview/module.php:266 pageContent() #8 /module.php:25 modAction('page')

**Comment by curtisdelicata** [comment]
Commenting out $mediaobject = $person->findHighlightedMedia();
and setting $mediaobject let me use the module for now.

**Comment by melizaa** [comment]
I get the same error

**Comment by JustCarmen** [comment]
After more than 4 years I've released a new version of the module for webtrees 2. At the moment it is in beta state but I encourage you to try it out.

I will close all old issues. But if you think this issue still stands you can re-open this issue or create a new one.
