### ISSUE TITLE
script in wrong place

### ISSUE THREAD

**Issue by curtisdelicata** [JustCarmen/webtrees-fancy-treeview#63]
Fancy Tree View code is outside of the document and loaded on every page.

<script>
          var newSheet=document.createElement("link");
          newSheet.setAttribute("rel","stylesheet");
          newSheet.setAttribute("type","text/css");
          newSheet.setAttribute("href","/modules_v3/fancy_treeview/css/style.css");
          document.getElementsByTagName("head")[0].appendChild(newSheet);
        </script><!DOCTYPE html>

**Comment by JustCarmen** [comment]
After more than 4 years I've released a new version of the module for webtrees 2. At the moment it is in beta state but I encourage you to try it out.

I will close all old issues. But if you think this issue still stands you can re-open this issue or create a new one.
