### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by enes73** [JustCarmen/webtrees-fancy-treeview#68]
Hello,

I have strange situation... I put 2 root persons (2 Fancy Tree pages) and on one root person EVERYTHING WORKING WELL, but on other root person I receive just blank page. If from URL I remove "&ged=XXXXXX" (XXXXXX - name of my Gedcome file) then I receive all expected data?! ALSO, if I not loged in, this "problematic" root person works..... I got expected data immediately!?

Can you somehow help me to find where/what is a problem? For additional data, please ask...

Thanks in advanced!
Enes

**Comment by JustCarmen** [comment]
A blank page often means a fatal error occurs. See [webtrees.github.io/faq/500
](https://webtrees.github.io/faq/500)

What does the error message say?

**Comment by ANusselt** [comment]
I faced the same issue and could "resolve" it.

1. I went through the individuals in the regular webtrees frontend and checked the "Descendants" tab and its contents
2. I figured out, that some individuals contain content here, some are not
3. I rearranged families and tried to see what happened when I deleted relationships of child 

In the end it was something really strange. I had no clue, what it was and so I decided to delete the individual which seems to raise this problem and reentered it. It worked.

But after I linked an existing media to it (picture), the same problem occurred. So far I have no clue, why this is relevant for the tree, but without linking this media it works.

Hope that helps.

**Comment by enes73** [comment]
mod_fcgid: stderr: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 704512 bytes) in /home/enes/public_html/stablo/modules_v3/fancy_treeview/app/FancyTreeviewClass.php on line 432, referer: http://enes.iz.rs/stablo/module.php?mod=fancy_treeview&mod_action=page&rootid=i4020&ged=STABLO


Problem is been low memory limit. I just increased memory limit from default value 128M to 256M (in Control panel: Website->Website preferencies), and all works well.

Thanks.

**Comment by enes73** [comment]
EDIT:

After rise memory limit, I got data on HTML page (there is a lot data). BUT, when I click on PDF icon (try to download PDF file, after couple seconds (5-6 sec.) I got error: **The file XXXXXXXXX.pdf could not be created.**
![Capture](https://user-images.githubusercontent.com/6985394/80641151-b702d400-8a64-11ea-8241-6aa46e05479c.JPG)

I cannot find what I need to check/fix to be able to download (maybe large) PDF file. I expect that PDF filesize is 1-2 MB, but I think this is not too large file?

**Comment by JustCarmen** [comment]
After more than 4 years I've released a new version of the module for webtrees 2. At the moment it is in beta state but I encourage you to try it out.

I will close all old issues. But if you think this issue still stands you can re-open this issue or create a new one.
