### ISSUE TITLE
When will version 2.0 be supported?

### ISSUE THREAD

**Issue by DaPoHou** [JustCarmen/webtrees-fancy-treeview#70]
This module is very helpful. When will the WebTrees version 2.0 be perfectly supported?

**Comment by spikerguy** [comment]
@JustCarmen  Any plan on upgrading it to V2?

Thanks.

**Comment by Fa10175** [comment]
This module is very helpful for me in v1.7
I know you are busy and it not so easy to upgrade the source from 1.7 to 2.0.
i would like to help you but my knowledge in PHP is very poor...
May be some other developper could help you ...
Any plan on upgrading it to V2 in 2022?

Thanks for you for all good modules.

**Comment by baskar-yahoo** [comment]
Looking forward to seeing the wt2.0

Many thanks for all the nice modules.  Specifically for justlight and fancy treeview module

**Comment by JustCarmen** [comment]
After more than 4 years I've released a new version of the module for webtrees 2. At the moment it is in beta state but I encourage you to try it out.

I will close all old issues. But if you think this issue still stands you can re-open this issue or create a new one.
