### ISSUE TITLE
Fancy Treeview & PDF 1.7.11 - unnecessary comma at marriage without a wedding date but with parents of the married person

### ISSUE THREAD

**Issue by TheDutchJewel** [JustCarmen/webtrees-fancy-treeview#71]
In the case of a marriage **without** a wedding date but **with** parents of the married person, there is an unnecessary comma directly for the dot at the end of the sentence:

`He married [name whife], daughter of [name father and mother],.`

Is it possible to remove that comma?

**Comment by JustCarmen** [comment]
After more than 4 years I've released a new version of the module for webtrees 2. At the moment it is in beta state but I encourage you to try it out.

I will close all old issues. But if you think this issue still stands you can re-open this issue or create a new one.
