### ISSUE TITLE
Fancy Treeview & PDF - remove period after last number of a numbered list

### ISSUE THREAD

**Issue by TheDutchJewel** [JustCarmen/webtrees-fancy-treeview#72]
I like the output of the reports except for the period (.) after the last number of the numbered list like:
```
1.1.
1.1.1.
```

Without that last period it should look like:
```
1.1
1.1.1
```

Is it possible to remove the period after the last number of a numbered list in the web and pdf output?

**Comment by JustCarmen** [comment]
After more than 4 years I've released a new version of the module for webtrees 2. At the moment it is in beta state but I encourage you to try it out.

I will close all old issues. But if you think this issue still stands you can re-open this issue or create a new one.
