### ISSUE TITLE
Call to a member function canShow() on null

### ISSUE THREAD

**Issue by hartenthaler** [JustCarmen/webtrees-fancy-treeview#73]
It is great that this module will be available again. It was my most missed module looking back to webtrees 1.7. I know that you are still working on it, so the following error is not so important. It appears only from time to time. 

> Call to a member function canShow() on null …/modules_v4/jc-fancy-treeview/FancyTreeviewModule.php:419
> #0 …/app/Module/ModuleThemeTrait.php(494): JustCarmen\Webtrees\Module\FancyTreeview\FancyTreeviewModule->getMenu()
> #1 [internal function]: Fisharebest\Webtrees\Module\WebtreesTheme::Fisharebest\Webtrees\Module\{closure}()

Give me a signal when you think that it is the right time that I could support you by doing some tests or adding a more complete translation to German. I would be glad to support you.

**Comment by JustCarmen** [comment]
Hi Herman, I've just released the first beta version of the Fancy Treeview module for webtrees 2. Would you please test it and let me know if this error still occurs? I can't reproduce it which makes it hard to solve.

>  It appears only from time to time

If it happens again, can you give me some clues of what you did right before the error occurs?

> Give me a signal when you think that it is the right time that I could support you by doing some tests or adding a more complete translation to German. I would be glad to support you.

Here is the signal :). You can find the German translation at [poeditor.com](https://poeditor.com/projects/view?id=564845)

Thanks for your help.

**Comment by hartenthaler** [comment]
Thank you! I'm testing now.

The translation is done.

**Comment by hartenthaler** [comment]
This error never occurred.
