### ISSUE TITLE
2.0.0-beta FancyTreeviewModule::checkPrivacy()

### ISSUE THREAD

**Issue by TheDutchJewel** [JustCarmen/webtrees-fancy-treeview#74]
I installed the module in webtrees 2.1.7, and disabled all other modules.

But on all individual pages I get this error message::
![afbeelding](https://user-images.githubusercontent.com/46184729/204074250-7645070d-a9dc-44c5-935b-518a772863e4.png)

Tested on Win10 22H2 with xampp v7.4.33-0.

**Comment by JustCarmen** [comment]
Thanks for reporting. This is a problem with your PHP version. It works in PHP 8, but it should work with PHP 7.4 since this version is supported by webtrees 2.

**Comment by JustCarmen** [comment]
I've fixed this, but you should be aware that the life of PHP 7.4 ends within a few days.

However webtrees will support it for some time. See: https://www.webtrees.net/index.php/en/forum/2-open-discussion/37466-end-of-life-of-php-7-4
