### ISSUE TITLE
Adopted and foster status are not shown

### ISSUE THREAD

**Issue by hartenthaler** [JustCarmen/webtrees-fancy-treeview#75]
The status "adopted" or "foster" of a child is not shown in the narrative story, but there are translation strings for such situations available.

**Comment by hartenthaler** [comment]
When testing this function I used a foster child in my tree. There is in the INDI record of this child
```
1 FAMC @F765@
2 PEDI foster
```
Maybe there is a problem with your function "checkPedi". I'm using in my extended family module a more complex function (maybe it helps to solve this issue, but I can't remember why I have done it that way and why I used the maybe not so performant function "Registry::elementFactory()->make('INDI:FAMC:PEDI')->value($pedi, $child->tree())").
```
    /**
     * generate a translated pedigree label for a child
     * GEDCOM record could be for example "1 FAMC @xref@\n ...\n2 PEDI adopted"
     *
     * @param Individual $child
     * @return string
     */
    private static function generatePedigreeLabel(Individual $child): string
    {
        $label = '';
        if ($child->childFamilies()->first()) {
            $fact = $child->facts(['FAMC'])->first();
            if ($fact instanceof Fact) {
                $pedi = $fact->attribute('PEDI');
            } else {
                $pedi = '';
            }
            if ($pedi !== '' && $pedi !== PedigreeLinkageType::VALUE_BIRTH) {
                $label  = Registry::elementFactory()->make('INDI:FAMC:PEDI')->value($pedi, $child->tree());
            } else {
                $label  = Registry::elementFactory()->make('INDI:FAMC:PEDI')->value('', $child->tree());
            }
        }
        return $label;
    }    
```

**Comment by JustCarmen** [comment]
Thanks for the code. It helped me to find the error, but the label text cannot be used here. It gives only the relationship from parent to child (e.g. foster parent). I need the relationship from child to parent (e.g. foster child). This is not part of webtrees so I reused the code from fancy treeview 1.
