### ISSUE TITLE
Translation of 'Ancestors'

### ISSUE THREAD

**Issue by hartenthaler** [JustCarmen/webtrees-fancy-treeview#76]
In FancyTreeviewModule.php in line 265 there is
`strtolower(I18N::translate('Ancestors'))`
The strtolower function should not be used at least for the German language.

**Comment by JustCarmen** [comment]
I use the default webtrees translations strings when possible. In webtrees there is already a translation string for Ancestors (with a capital). But we need it lowercase, at least in Dutch. But I now realise that in German nouns are written with a capital and that might be the case for some other languages too.

I think the whole line should be changed to:
` I18N::translate('Descendants and ancestors')`

Then you can translate both words with a capital, while in other languages the translation of ancestors remains in lowercase.

**Comment by mpwt** [comment]
Same with children - Children / Kinder is a noun and is capitalized in German:

![7C69E290-3071-481F-9111-421791B9F575](https://user-images.githubusercontent.com/16311627/204097610-d0fc50e3-2017-44b3-9555-6ccf30226e7d.jpeg)
