### ISSUE TITLE
Allow option to show place names in a short version

### ISSUE THREAD

**Issue by hartenthaler** [JustCarmen/webtrees-fancy-treeview#77]
In the narrative story, long place names are a bit disturbing, for example: "She was born in Sigmaringen, Sigmaringen, Baden-Württemberg, Deutschland". Maybe you can add an option (like in the GVExport custom module) that allows shortening such place names.

**Comment by JustCarmen** [comment]
Do you want to abbreviate all place names or only the place names in your own country? If the place is abroad, it might be clearer to include the country (using the first and last part of the place name).

In the previous version of the module you could enter your home country. Places within your home country were shortened, but places abroad were not. I've stripped out some of these extra options to clear up the code and to get the basis up and running in webtrees 2. Some (not all) of these options will eventually return if wanted.

**Comment by mpwt** [comment]
The setting in webtrees should be used. Thanks a lot for your work.

**Comment by hartenthaler** [comment]
This feature request is not important at the moment. So postpone it. 

I can think about the following options
- show it as it is defined in webtrees (all hierarchy levels)
-  define a home country; show all levels for abroad locations and only the first level in the home country
- show only the lowest and the highest level

**Comment by hartenthaler** [comment]
Thank you! It works perfectly. I like it!
