### ISSUE TITLE
Wrong translation for "Show descendants" button

### ISSUE THREAD

**Issue by Jefferson49** [JustCarmen/webtrees-fancy-treeview#78]
The German translation for the top right button "Show descendants" is wrong; it should be "Nachkommen anzeigen" (or "Zeige Nachkommen"). However, there is no translation item available in poeditor.com.

![Fancy](https://user-images.githubusercontent.com/81484983/204121096-d7caa9d5-b12e-40e3-bb2d-16e33d742449.JPG)

**Comment by JustCarmen** [comment]
This is fixed with the same commit that fixes #76: https://github.com/JustCarmen/webtrees-fancy-treeview/commit/e0da23f3b3750ded4ecc0d9fc344c8f8691ac3fd
