### ISSUE TITLE
Option to not display married couples as having had no children

### ISSUE THREAD

**Issue by rbader** [JustCarmen/webtrees-fancy-treeview#81]
If a living person's privacy restrictions for their name and birth date have been set to 'show to visitors' (2 RESN none) they are displayed with these details. However, underneath their details (whether they have a list of children or not) it currently reads:

"[first name] [last name] had none children." 

This sentence does not appear for deceased persons. It should not appear for living persons (with or without children) whose name and birth date are visible to visitors.

**Comment by rbader** [comment]
I have just realised that this appears to be related to the sentence that appears in the new module for each married couple that has had no children. It would be good if one could opt out of having this information about couples with no children displayed.

**Comment by JustCarmen** [comment]
I see something is indeed going wrong there. I'm going to look into it.
