### ISSUE TITLE
Marriages are shown in incorrect order

### ISSUE THREAD

**Issue by RH67dev** [JustCarmen/webtrees-fancy-treeview#82]
Using webtrees 2.1.8 and noticed the marriages are shown in an incorrect order.
My ex-wife is listed as second and my current wife is shown as my first marriage

**Comment by JustCarmen** [comment]
Are you sure the marriages are listed in the correct order in the Gedcom? I checked several marriages and indeed found one listed in the wrong order on the Fancy Treeview page but this one appears to be in the incorrect order in the Gedcom. The marriages are listed in the order they appear in Gedcom which is also the default in webtrees.

**Comment by RH67dev** [comment]
Ah did not check that :-(
Yes it was ordered incorrect in Gedcom, after re-ordering it displays fine.

Thanks for your quick reply !
