### ISSUE TITLE
Descendants not complete?

### ISSUE THREAD

**Issue by heiler** [JustCarmen/webtrees-fancy-treeview#89]
Descendants seem to me are not completely shown. I encl. an example: My Grandfather had 7 children, only 3 are shown. Maybe the filter is whether or not the children were married. Would this be intended?

[nachkommen.txt](https://github.com/JustCarmen/webtrees-fancy-treeview/files/10123549/nachkommen.txt)

**Comment by JustCarmen** [comment]
I mentioned it in the forum post, but maybe you overlooked it. Currently there is no configuration page in this beta version. If you want to test the available options, open the file FancyTreeviewModule.php file and scroll down to the function 'options' (from line 438). Alter the values here. The configuration page will probably be added before the first stable release.

By default, the show_singles option is set to '0' (= no). Change the value to '1' (= yes) to include singles in the overview. By default, only individuals with a spouse and/or children are followed to the next generation.

**Comment by JustCarmen** [comment]
This is fixed with this commit: 62381f614488333971590ad8e8c78d308e6d1255

It is now possible to set the 'show singles' option to 'yes'. In this case, singles without a partner and children are also detailed in the next generation.
