### ISSUE TITLE
Padding on images

### ISSUE THREAD

**Issue by WGroleau** [JustCarmen/webtrees-fancy-treeview#90]
It would be a minor improvement in appearance if there were a tiny bit of white space around the images, so the text letters don't actually touch the picture.  I usually use five pixels of padding, but I also use bigger images, so maybe five might be too much for images of the size you use.

**Comment by JustCarmen** [comment]
Yes, there was an issue with some browsers where the padding wasn't working as expected. But this is solved with this commit: https://github.com/JustCarmen/webtrees-fancy-treeview/commit/7a953c321fdb33e68e75b2461856e4ad17b2bcb7

I plan to release a second beta version soon with the improvements already made thanks to input of the beta testers.
