### ISSUE TITLE
Wrong German translation for "Show descendants" and "Show ancestors" buttons

### ISSUE THREAD

**Issue by Jefferson49** [JustCarmen/webtrees-fancy-treeview#93]
Although loading the latest German .po file from [poeditor.com](https://poeditor.com/join/project/9HqYANIknp) and updating the .mo file, I still get a wrong translation for the "Show descendants" and "Show ancestors" buttons. 

Maybe, these buttons are not included in the translation? Or they are following some other webtrees based translation?

![Zeigen nachkommen](https://user-images.githubusercontent.com/81484983/205346787-33c3f93b-cca5-4c1f-b28c-91d9219ea016.JPG)
![Zeigen vorfahren](https://user-images.githubusercontent.com/81484983/205346788-4576f691-4285-4a86-baf8-9c0f3dc44ab3.JPG)

**Comment by JustCarmen** [comment]
The text is changed: 
https://github.com/JustCarmen/webtrees-fancy-treeview/blob/main/resources/lang/de.po
https://poeditor.com/projects/po_edit?per_page=20&id=564845&id_language=55&filter=&order=&search=show


If you have downloaded a MO-file from Poeditor or compiled it yourself, you should see the changes. If not, maybe clear your cache.

**Comment by Jefferson49** [comment]
Clearing my browser cache did not help.

With a look into the code, I recognized that this issues has already been fixed in the latest code: https://github.com/JustCarmen/webtrees-fancy-treeview/commit/e0da23f3b3750ded4ecc0d9fc344c8f8691ac3fd
