### ISSUE TITLE
If English language is selected, occupations in German are shown in lower case

### ISSUE THREAD

**Issue by Jefferson49** [JustCarmen/webtrees-fancy-treeview#94]
Occupations in German are shown in lower case, if English language is chosen, e.g.:
- Hausfrau => hausfrau
- Bergbauingenieur, Hüttenvogt => bergbauingenieur, Hüttenvogt 

In the second example, the first occupation word is lower case, the second word keeps upper case.

Well, before GEDCOM 7 (with translation features included) there is probably no good solution for this. However, changing to lower case it worse than doing nothing and should be avoided. 

I would propose to leave data from the OCCU tags (and probably also from other tags) as it is.

![occupation](https://user-images.githubusercontent.com/81484983/205350696-000d270c-89c6-4dfa-8753-3e2027969072.JPG)

**Comment by JustCarmen** [comment]
You have selected English. If you select German you'll see the occupations with a capital. I've made an exception for German.
In many languages, like English and Dutch, occupations are written lowercase when the appear in the middle of a sentence which is the case here.

**Comment by JustCarmen** [comment]
I think I will add it to the configuration page as an option. That's the only way to keep everybody happy I think.

By the way, the configuration page is not ready yet. I still need to write it but it will be ready before the first stable release.

**Comment by Jefferson49** [comment]
Thank you for introducing the configuration option. I tested it in the new beta3 version and it worked fine!
