### ISSUE TITLE
Handling of different languages: GEDCOM.HEAD.LANG

### ISSUE THREAD

**Issue by ungeahnt** [JustCarmen/webtrees-fancy-treeview#98]
_Originally posted by @JustCarmen in https://github.com/JustCarmen/webtrees-fancy-treeview/issues/94

When you use the LANG tag from the GEDCOM.HEAD, then you could better adjust your spelling / capitalization. 

See GEDCOM 5.5.1 at page 23 and 51: 
```
HEAD {1:1}
...
+1 LANG <LANGUAGE_OF_TEXT> {0:1}
```
~[edit: LANGUAGE_PREFERENCE deleted]~

You would probably still have to query and create the tag in each family tree first. But this could also query webtrees as a required parameter when creating/importing a family tree?!

**Comment by JustCarmen** [comment]
The problem is that not every Gedcom contains this header information. Not even a Gedcom exported from webtrees.

**Comment by ungeahnt** [comment]
> The problem is that not every Gedcom contains this header information. Not even a Gedcom exported from webtrees.

So, why not a simple text description that `HEAD.LANG` must be set by the user for correct capitalization? Or why not query the user (e.g. in modul config-panel) for `HEAD.LANG` and add the value to the GEDCOM? 

The [feature request in #94](https://github.com/JustCarmen/webtrees-fancy-treeview/issues/94#issuecomment-1336142073) would add a option in config-panel. 

For some reason I think that querying `LANG` provides more flexibility (e.g. for future special cases in other languages).

**Comment by JustCarmen** [comment]
> So, why not a simple text description that HEAD.LANG must be set by the user for correct capitalization?

Does every user know how to manually add information to a Gedcom? Is this something that should be encouraged?

> Or why not query the user (e.g. in modul config-panel) for HEAD.LANG and add the value to the GEDCOM?

Because I didn't know that and frankly I have no idea how to implement that in the code. Moreover, I don't think this module should write information to the Gedcom file.

> The https://github.com/JustCarmen/webtrees-fancy-treeview/issues/94#issuecomment-1336142073 would add a option in config-panel.

That is correct. That was the most pragmatic solution.

For some reason I think that querying LANG provides more flexibility (e.g. for future special cases in other languages).

I agree, but at the moment I don't have the faintest idea of how to practically implement that.

**Comment by JustCarmen** [comment]
> Type "HEAD" in the search and a GUI-Dialog opens. No big deal. No RAW-GEDCOM

I've learned something new today! When was that implemented? Never heard of it, never seen it before. Thanks.

**Comment by ungeahnt** [comment]
> ... I don't have the faintest idea of how to practically implement that.

Me even more ;)

> When was that implemented? Never heard of it, never seen it before.

No idea. I _think_ I've seen it in one of the forum/github posts in the last years ...
